---
tap_install:
  values:
    profile: build
    ceip_policy_disclosed: TRUE
    supply_chain: basic
    namespace_provisioner:
      controller: true
      additional_sources:
  # Add templated Grype scan policy and java Tekton pipeline
      - git:
          ref: origin/main
          subPath: namespace-provisioner-gitops-examples/custom-resources/testing-scanning-supplychain
          url: https://github.com/sethiyash/application-accelerator-samples.git
        path: _ytt_lib/testingscanning
      # Add templated snyk scan policy
      - git:
          ref: origin/main
          subPath: namespace-provisioner-gitops-examples/custom-resources/scanpolicies
          url: https://github.com/sethiyash/application-accelerator-samples.git
        path: _ytt_lib/scanpolicies
